# Basic information:
title: 'lucasof'
base-url: 'D:\Development\lucasof\lucasof.site-sliver\build\'
lang: en
authors: []
version: 1.0

post-output: 'article' # Here is the name of the folder in which the articles will be.
templates: ['header.css', 'style.css', 'footer.css', 'blog.css'] # Styles to be included
html-pages: ['index.html', 'blog.html', 'whoami.html', 'contact.html', 'projects.html', '404.html'] # Pages to be included

